- cloudbuild.yaml
- udfs/cloudbuild.yaml
Updating to use the cloud sdk image hosted on docker according to guidance from https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
> Update to newer cloud sdk image

- tools/sql_extraction/README.md
- tools/sql_extraction/build.gradle.kts
- tools/sql_extraction/examples/ConcatTest.java
- tools/sql_extraction/examples/IfElseTest.java
- tools/sql_extraction/examples/JDBCTest.java
- tools/sql_extraction/examples/LoopTest.java
- tools/sql_extraction/examples/SimpleStringTest.java
- tools/sql_extraction/src/main/kotlin/App.kt
- tools/sql_extraction/src/main/kotlin/Cli.kt
- tools/sql_extraction/src/main/kotlin/FileListExpander.kt
- tools/sql_extraction/src/test/kotlin/FileListExpanderTest.kt
- tools/sql_extraction/src/test/resources/junit-platform.properties
- added `examples` directory with java files to use as example inputs
- added a command line arguments library, with current options following:
```
Usage: sql_extraction [OPTIONS] [FILEPATHS]...
Options:
-r, --recursive  scan files in subdirectories recursively
-h, --help       Show this message and exit
Arguments:
FILEPATHS  file and directory paths to code
```
- added basic file list expander (converts directories to list of files) and unit tests
Support for features such as globs/file extension support will be added in a future commit
> SQL Extractor: java examples, cli, file list expander and unit tests

- tools/sql_extraction/README.md
- tools/sql_extraction/build.gradle.kts
- tools/sql_extraction/src/main/kotlin/Cli.kt
- tools/sql_extraction/src/main/kotlin/DataFlowEngine.kt
- tools/sql_extraction/src/main/kotlin/DataFlowSolver.kt
- tools/sql_extraction/src/main/kotlin/FileListExpander.kt
- tools/sql_extraction/src/main/kotlin/FrontEnd.kt
- tools/sql_extraction/src/main/kotlin/JavaFrontEnd.kt
- tools/sql_extraction/src/main/kotlin/SqlExtractor.kt
- tools/sql_extraction/src/main/kotlin/output/Location.kt
- tools/sql_extraction/src/main/kotlin/output/Output.kt
- tools/sql_extraction/src/main/kotlin/output/Query.kt
- tools/sql_extraction/src/main/kotlin/output/QueryFragment.kt
- tools/sql_extraction/src/test/kotlin/DataFlowSolverTest.kt
- tools/sql_extraction/src/test/kotlin/SqlExtractorTest.kt
- tools/sql_extraction/src/test/resources/simplelogger.properties
To analyze each file, both a frontend and a data-flow engine are required. The frontend reads through the language-specific AST in program order and calls necessary methods in the engine (e.g. foundLiteral, foundUsage, etc). The AST parser and visitor are provided by Antlr. Since this commit was getting massive, the engine implementation and other details will be on a future commit.
Resulting list of queries are converted to JSON and printed to STDOUT.
> SQL Extraction: setup data pipeline (frontends, json output)

- tools/sql_extraction/README.md
- tools/sql_extraction/src/main/kotlin/Cli.kt
- tools/sql_extraction/src/main/kotlin/DataFlowEngine.kt
- tools/sql_extraction/src/main/kotlin/DataFlowSolver.kt
- tools/sql_extraction/src/main/kotlin/FilesExpander.kt
- tools/sql_extraction/src/main/kotlin/FrontEnd.kt
- tools/sql_extraction/src/main/kotlin/JavaFrontEnd.kt
- tools/sql_extraction/src/main/kotlin/SqlExtractor.kt
- tools/sql_extraction/src/main/kotlin/output/Location.kt
- tools/sql_extraction/src/main/kotlin/output/Query.kt
- tools/sql_extraction/src/main/kotlin/output/QueryFragment.kt
- tools/sql_extraction/src/test/kotlin/DataFlowSolverTest.kt
- tools/sql_extraction/src/test/kotlin/FilesExpanderTest.kt
- tools/sql_extraction/src/test/kotlin/SqlExtractorTest.kt
I did some refactoring on the SQL Extraction project
- fixed minor mistake in readme (run -> build)
- made relevant classes input/output sequences (like Java streams but in Kotlin) instead of some other data structure
- made DataFlowSolver retrieve the queries from the engine rather than the frontend
- renamed FileListExpander to FilesExpander
- made QueryFragment immutable
- implemented Comparable for Location
> SQL Extraction: refactor to use sequences

- tools/vscode_sql_extraction/package.json
- tools/vscode_sql_extraction/src/extension.ts
- tools/vscode_sql_extraction/src/query.ts
- tools/vscode_sql_extraction/src/tree_view.ts
1. Renamed command to be more specific (Find All Embedded SQL Queries)
2. Moved tree view-related classes to their own file
3. Added all created VS Code elements to subscriptions so that they are disposed when this extension is disabled
> SQL Extraction: minor VS Code refactoring

- tools/automatic_query_fixer/build.gradle
- tools/automatic_query_fixer/src/main/java/com/google/cloud/bigquery/utils/queryfixer/QueryFixerMain.java
Modify the build to fit in frontend.
Move the print of input query to natural-language output only.
> Auto Query Fixer: Refactor the build and main class for frontend

- tools/vscode_automatic_query_fixer/.gitignore
- tools/vscode_automatic_query_fixer/copy_binaries.js
- tools/vscode_automatic_query_fixer/package-lock.json
- tools/vscode_automatic_query_fixer/package.json
- tools/vscode_automatic_query_fixer/resources/MockAutoFixer
- tools/vscode_automatic_query_fixer/src/auto_fixer_result.ts
- tools/vscode_automatic_query_fixer/src/auto_fixer_runner.ts
- tools/vscode_automatic_query_fixer/src/code_action_provider.ts
- tools/vscode_automatic_query_fixer/src/extension.ts
The copy_binaries and auto_fixer_runner were copied over from the SQL Extraction VS Code extension. I could invest in a way to combine them later. Additionally, the auto_fixer_results are simply for the JSON format definition.
The extension should now be fully integrated with @mingen-pan's Auto Fixer.
> VSCode Auto Fixer: display error highlights and code fixes

- tools/zetasql_helper/zetasql_helper/local_service/BUILD
- tools/zetasql_helper/zetasql_helper/local_service/local_service.cc
- tools/zetasql_helper/zetasql_helper/local_service/local_service.h
- tools/zetasql_helper/zetasql_helper/local_service/local_service.proto
- tools/zetasql_helper/zetasql_helper/local_service/local_service_grpc.cc
- tools/zetasql_helper/zetasql_helper/local_service/local_service_grpc.h
- tools/zetasql_helper/zetasql_helper/local_service/local_service_test.cc
- tools/zetasql_helper/zetasql_helper/scanner/BUILD
- tools/zetasql_helper/zetasql_helper/scanner/extract_function.cc
- tools/zetasql_helper/zetasql_helper/scanner/extract_function.h
- tools/zetasql_helper/zetasql_helper/scanner/function_range.proto
- tools/zetasql_helper/zetasql_helper/scanner/locate_table.cc
- tools/zetasql_helper/zetasql_helper/scanner/locate_table.h
- tools/zetasql_helper/zetasql_helper/scanner/scanner_test.cc
Develop ExtractFunctionRange, LocateTableRanges, and GetAllKeywords methods
RPC calls are added
Test cases are included.
> Auto Query Fixer: Implement ExtractFunctionRange, LocateTableRanges, GetAllKeywords methods in ZetaSQL Helper server

- views/audit/README.md
Under Prerequsites section of README.md- #3 and #4 , there is reference to a non-existent file - [big_query_elt_audit_log_v2.sql](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/views/audit/big_query_elt_audit_log_v2.sql.
I think this should be updated to
big_query_elt_script_logging.sql instead.
> Update README.md to correct non-existent link to big_query_elt_audit_log_v2.sql file (404 error) 

- udfs/community/README.md
- udfs/community/levenshtein.sql
- udfs/community/test_cases.yaml
A UDF that computes the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between two strings. 
This code is based on the 2019 PR #26 by @davetemplin, still unmerged, adding all the suggestions (.js file hosting process, test cases) by @danieldeleo.
I've followed the instructions at [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/CONTRIBUTING.md) but I get an error related to the JS location bucket
```
/home/sergi/.local/share/virtualenvs/udfs-xmmKslJq/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py:662: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <google.cloud.bigquery.job.query.QueryJob object at 0x7fa8cb9816d0>, timeout = None
retry = …
```
> Adding levenshtein to bigquery-utils

- udfs/tests/Dockerfile.ci
- udfs/tests/udf_test_utils.py
Removing caret symbol from js libs specification so that the exact version of a library is built, instead of a greater version.
> Fix for js UDF dependency generation

- tools/query_breakdown/pom.xml
- tools/query_breakdown/src/main/java/com/google/bigquery/Main.java
Remove log4j dependency. This log4j version is not between 2.0 and 2.15 and therefore not vulnerable. However, the version is quite low and not very useful, so remove the depdency.
> remove log4j dependency

- dataform/examples/dataform_datavault/README.md
Change authentication step to use application default credentials as [shown here](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/dataform/examples/dataform_udf_unit_test/tutorial.md#2-generate-the-dataform-credentials-file-by-running-the-following) instead of using the downloaded service account key
> Authentication step to use ADC

- scripts/billing/sql/monthly_invoice_costs_credits.sql
**Issue**
BigQuery billing analytics [monthly_invoice_costs_credits.sql](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/scripts/billing/sql/monthly_invoice_costs_credits.sql) script uses join to unnest credits and adds them to total cost. This produces duplicate cost rows and incorrect total cost when there is more than one credit applied to the same line item.
**Fix**
Join is replaced with subquery to prevent duplication of rows which fixes the total cost.
> Fix billing analytics SQL script

- udfs/deploy.yaml
This PR addresses the following error when invoking `deploy.yaml` with a user-specified build service account:
```
Your build failed to run: generic::invalid_argument: generic::invalid_argument: if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket' (b) use the CLOUD_LOGGING_ONLY logging option, or (c) use the NONE logging option
```
> Adding explicit logging option to deploy.yaml

- udfs/community/README.md
- udfs/community/test_cases.js
- udfs/community/url_parse.sqlx
We can use underscore and tilde in URL. I have made them capturable.
> Characters that are allowed in a URI but do not have a reserved
> purpose are called unreserved. These include uppercase and lowercase
> letters, decimal digits, hyphen, period, underscore, and tilde.
- [RFC 3986: Uniform Resource Identifier (URI): Generic Syntax](https://www.rfc-editor.org/rfc/rfc3986#section-2.3)
> Patch: enable UDF "url_param" to handle tildes and underscores

- udfs/deploy.yaml
Parameterizing the dir attribute in the deploy.yaml config allows:
- Users to manually submit builds from the udfs/ directory using gcloud 
- Build triggers at repo root level can override this attribute to prevent path failures
> Parameterize the deploy.yaml build config working directory 

- tools/query_breakdown/pom.xml
There are 1 security vulnerabilities found in com.google.guava:guava 29.0-jre
- [CVE-2020-8908](https://www.oscs1024.com/hd/CVE-2020-8908)
Upgrade com.google.guava:guava from 29.0-jre to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade com.google.guava:guava to 30.0-jre

- udfs/community/test_cases.js
- udfs/community/typeof.sqlx
Improvement to the `typeof()` UDF: correctly recognize more (all?) strings.
`FORMAT('%T', <string value>)` will return a string with single quotes if the passed string value contains a double quote (`"`) and no single quotes (`'`). `typeof()` would no recognize that as a string, and return `"UNKNOWN"`.
> typeof() UDF improvement: correctly identify single quoted string

- views/migration/teradata/README.md
- views/migration/teradata/sys_calendar.sql
This will help people migrating code from Teradata to BigQuery. Placing this in views/migration/teradata to mimic the structure of the UDF directories. So far there seems to be no test infrastructure for views, so let me know what, if anything, needs to be done to test this. So far this has just been manually tested.
> Add a view that emulates the SYS_CALENDAR.CALENDAR table from Teradata

- udfs/community/README.md
- udfs/community/json_extract_keys.sqlx
- udfs/community/json_extract_values.sqlx
- udfs/community/test_cases.js
In BigQuery SQL function behavior,
function typically would return null for invalid arguments, not causing runtime error. JavaScript UDF currently does.
The difference is not useful for users because it gives users extra attention to use JavaScript UDFs
This PR fixes behavior of json_extract_keys, json_extract_values
> Handling Invalid input for  `fn.json_extract_keys`,  `fn.json_extract_values`

- udfs/community/README.md
- udfs/community/cw_signed_leftshift_128bit.sqlx
- udfs/community/cw_signed_rightshift_128bit.sqlx
- udfs/community/test_cases.js
UDFs for right/left bit shift of signed 128-bit integer (which is modeled as BIGNUMERIC with 0 scale).
> Translation Engine UDF for signed 128bit bitshift.

- tools/protobuf_export/.gitignore
- tools/protobuf_export/README.md
- tools/protobuf_export/index.js
- tools/protobuf_export/package.json
- tools/protobuf_export/protos/dummy.proto
- tools/protobuf_export/tutorial.md
- tools/protobuf_export/webpack.config.js
In Order to support Protobuf export from BigQuery, a process has to be followed, as this is not supported by default.
The process is defined for anyone wishing to export a protobuf column to use.
> Add Protobuf Export to BigQueryUtils/Tools

- udfs/community/README.md
- udfs/community/cw_split_part_delimstr_idx.sqlx
- udfs/community/test_cases.js
This adds a function for emulating snowflake split_part. This function has the following semantics:
- The part index is 1-based
- However, index 0 is treated as 1
- Negative numbers are interpreted as indexes from the end of the string
It will help customers migrate from Snowflake to BigQuery.
> [UDF] Add UDF for emulating snowflake split_part

- udfs/community/cw_split_part_delimstr_idx.sqlx
- udfs/community/test_cases.js
- when there's an empty delimiter, the first part is the input string (don't split into individual characters)
- when there's an out-of-bounds value, the return value is an empty string ("") rather than NULL
> [UDF] Improve emulation of Snowflake SPLIT_PART

- udfs/community/README.md
- udfs/community/cw_regexp_extract.sqlx
- udfs/community/cw_regexp_extract_all.sqlx
- udfs/community/test_cases.js
Fixed following issue with `cw_regexp_extract` and `cw_regexp_extract_all` UDFS:
1. When no match occurs then UDF returns null instead of throwing error
2. When any of the input to UDFs is null then it returns null instead of throwing error.
> Fix edge cases in JavaScript regexp_extract and regexp_extract_all UDFs

- udfs/community/README.md
- udfs/community/cw_regexp_substr_4.sqlx
- udfs/community/test_cases.js
Like `regex_substr_5`, after successful regex match `regex_substr_4` should return entire matched substring and not just the first group that is matched. With this fix, UDF exhibits the behavior that is consistent with other regex UDFs such as `cw_regex_extract`, `cw_regex_substr_5` etc.
> Fixes issue in `regex_substr_4` function when regex has groupings.

- udfs/community/cw_regexp_instr_3.sqlx
- udfs/community/test_cases.js
The `start` argument in `cw_regexp_instr_3`  is 1-based, we allow for `start <= 0` and consider it as `1` for compatiblity.
> [UDF] Fix `cw_regexp_instr_3` assumption that `start` argument is 0-based.

- udfs/community/cw_td_strtok.sqlx
- udfs/community/test_cases.js
STRTOK in Teradata is a bit special (or rather, it's similar to libc's strtok, and that's a bit special):
- ignores leading delimiters
- ignores duplicate delimiters
- returns NULL for out-of-band fields
- except if the whole string consists of delimiters, and you want the first token, in which case it returns an empty string
> [UDF] Add strtok function for teradata emulation

- udfs/community/README.md
- udfs/community/cw_disjoint_partition_by_regexp.sqlx
- udfs/community/cw_overlapping_partition_by_regexp.sqlx
- udfs/community/test_cases.js
Following UDFs are added:
1. `cw_disjoint_partition_by_regexp` - Partitions rows into disjoint segments by matching their sequence with the provided regex pattern
2. `cw_overlapping_partition_by_regexp` - Partitions rows into overlapping segments by matching their sequence with the provided regex pattern
> Add `MATCH_RECOGNIZE` related UDFs to the community UDFs.

- udfs/community/test_cases.js
- udfs/community/typeof.sqlx
Slight modification for the new [RANGE type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#range_type).
> Case statements for the RANGE type.

- udfs/community/README.md
- udfs/community/studentt_cdf.sqlx
- udfs/community/test_cases.js
Adding `studentt_cdf` UDF. The UDF uses [jStat.studentt.cdf](https://jstat.github.io/distributions.html#jStat.studentt.cdf) function.
Returns the value of x in the cdf of the Student's T distribution with dof degrees of freedom.
Sample Query:
```SQL
SELECT `bqutils.fn.studentt_cdf`(1.0, 2.0) as studentt_cdf;
```
Results:
| Row | studentt_cdf      |
| --- | ----------------- |
| 1   | 0.788675134594813 |
> Adding studentt_cdf UDF

- udfs/community/kll_sketch_int64.sqlx
- udfs/community/theta_sketch_bytes.sqlx
- udfs/community/theta_sketch_int64.sqlx
- udfs/community/tuple_sketch_int64.sqlx
- udfs/datasketches/theta-sketch/theta_sketch.cpp
- udfs/datasketches/tuple-sketch/tuple_sketch.cpp
The existing implementations assume that merge() only ever happens after deserialization. This assumption is invalid, and the implementation should be correct for merge() directly after aggregation.
> [Sketch] Make merge more defensive for calling order

- stored_procedures/README.md
- stored_procedures/definitions/bqml_generate_embeddings.sqlx
Update the default batch size now that generate_embedding can handle a lot more rows.
Each individual job should take ~60-70 minutes.
> update embedding default batch size

- stored_procedures/definitions/bqml_generate_embeddings.sqlx
I was making use of the very awesome `bqml_generate_embeddings` stored procedure and noticed that for the target table, the full path wasn't wrapped in backticks in one spot which causes the call to fail if the project name or table name have odd characters (like a `-` for example)
> Fix embedding batch table path to be wrapped in backticks

- udfs/community/cw_regexp_replace_generic.sqlx
- udfs/community/test_cases.js
```sql
SELECT bqutil.fn.cw_regexp_replace_4('abaa', 'a', 'A', 1)
```
Current behavior:
```
AbAA
```
Expected behavior:
```
abAA
```
> fix: honor `offset` when `occurence` is 0

- udfs/community/cw_mode_boolean.sqlx
- udfs/community/cw_mode_bytes.sqlx
- udfs/community/cw_mode_date.sqlx
- udfs/community/cw_mode_float64.sqlx
- udfs/community/cw_mode_int64.sqlx
- udfs/community/cw_mode_json.sqlx
- udfs/community/cw_mode_numeric.sqlx
- udfs/community/cw_mode_string.sqlx
- udfs/community/cw_mode_timestamp.sqlx
- udfs/community/test_cases.js
For b/357127978
Unfortunately I can't declare these as
```sql
CREATE OR REPLACE AGGREGATE FUNCTION ${self()}(b ANY TYPE)
RETURNS ANY TYPE
....
```
I've also noticed that it is possible to overload on types for `CREATE TEMPORARY FUNCTION` but not `CREATE FUNCTION`, thus these all have their argument types in the name.
If I've missed a way to avoid duplicating the code, please let me know.
> Add functions for emulating Snowflake/Postgresql's mode()

- udfs/community/README.md
The current examples do not work. This is due to the project name being "bqutils" instead of "bqutil".
Fixing the typo means that the examples can now be copy-pasted and expected to work.
> Fix typos in community UDF examples

- stored_procedures/definitions/bqml_generate_text.sqlx
Fix for issue #475 that escapes `target_table` parameter
> escape target table parameter (#475)

- udfs/community/README.md
- udfs/community/cw_regexp_extract_all_start_pos.sqlx
- udfs/community/test_cases.js
Adds support for Snowflake and similar database systems that have `regexp_extract_all` / `regexp_substr_all` functions with a three-parameter signature where the third parameter in these functions specifies a 1-based start position for matching. This change addresses bug b/390757236.
> [Snowflake] Add a new UDF cw_regexp_extract_all_start_pos.
