GoogleCloudPlatform/bigquery-utils

udfs/migration/teradata/README.md
udfs/migration/teradata/decode1.sql
udfs/migration/teradata/decode2.sql
udfs/migration/teradata/decode3.sql

As Decode function in TD is multi-argument version, I've created 3 different methods to accept 1 to 3  search parameters. If PR is accepted I'm happy to continue and do 4-10 parameters.

Decode function from Teradata rewritten to BQ

---

udfs/community/README.md
udfs/community/random_value.sql

Adds a function which returns random values in an array. This function can be used to generate a dummy or anonymized dataset within a BigQuery query.

Add random_value function

---

udfs/migration/teradata/README.md
udfs/migration/teradata/left.sql
udfs/migration/teradata/right.sql

This implements the [LEFT](https://docs.teradata.com/reader/1DcoER_KpnGTfgPinRAFUw/Ef3DAn9emz~W57YSCkoEOQ) and [RIGHT](https://docs.teradata.com/reader/1DcoER_KpnGTfgPinRAFUw/4bAyNUOB6_VOuvSVrDRqDQ) functions of Teradata

implement teradata left and right functions

---

udfs/migration/teradata/README.md
udfs/migration/teradata/nvl.sql
udfs/migration/teradata/nvl2.sql

Add UDFs for Teradata [NVL](https://docs.teradata.com/reader/kmuOwjp1zEYg98JsB8fu_A/A3B8KYGf9EJhU2iCgqqrzw) and [NVL2](https://docs.teradata.com/reader/kmuOwjp1zEYg98JsB8fu_A/_77jzgn34QLLsZDslWefpw) functions

Add Teradata NVL and NVL2 functions

---

udfs/migration/teradata/README.md
udfs/migration/teradata/chr.sql

Create UDF for Teradata [chr](https://docs.teradata.com/reader/756LNiPSFdY~4JcCCcR5Cw/FUQ2~FCYkt6QoamvY1G4Cg) function

Add Teradata chr function

---

udfs/migration/redshift/README.md
udfs/migration/redshift/initcap.sql

Implement Redshift [INITCAP](https://docs.aws.amazon.com/redshift/latest/dg/r_INITCAP.html) function by making use of re2 [Unicode character class names \p{P} and \p{S}](https://github.com/google/re2/wiki/Syntax), and [order of regex alternatives](https://superuser.com/questions/1194399/does-order-of-alternatives-in-regex-matters)

Add Redshift INITCAP function

---

README.md

Added Stored_procedures dir to README.md

---

udfs/community/README.md
udfs/community/csv_to_struct.sql
udfs/community/find_in_set.sql
udfs/community/get_array_value.sql
udfs/community/get_value.sql
udfs/community/url_parse.sql

- csv_to_struct
- find_in_set
- get_array_value
- get_value
- url_parse
Happy to add the appropriate test yaml once #21 is merged.

Adds community udfs for dealing with csv and url

---

udfs/community/README.md
udfs/community/freq_table.sql

Construct a frequency table (histogram) of an array of elements.
Frequency table is represented as an array of STRUCT(value, freq)

Implementation of frequency table UDF

---

scripts/README.md

Fix broken link

---

udfs/community/README.md
udfs/community/test_cases.yaml
udfs/community/typeof.sql

I want to contribute dynamic `typeof` function written in BigQuery SQL UDF.
Test patterns are placed in this gist.
https://gist.github.com/apstndb/71b9a119ee16ffc4598e0af32678e4fe
https://stackoverflow.com/questions/43730045/bigquery-type-check-operator-like-typeof-in-javascript-or-workaround

Add typeof

---

udfs/migration/redshift/README.md
udfs/migration/redshift/split_part.sql
udfs/migration/redshift/test_cases.yaml

Implement Redshift [SPLIT_PART](https://docs.aws.amazon.com/redshift/latest/dg/SPLIT_PART.html) function

Add Redshift SPLIT_PART function

---

stored_procedures/get_next_id.sql

It generates next ids and inserts them into a sample table. This implementation prevents against race condition.

Create stored_procedure get_next_ids.sql

---

udfs/community/README.md
udfs/community/percentage_change.sql
udfs/community/test_cases.yaml

Contributing another frequently used calculation that'd be great to have available as a UDF.

UDF to calculate percentage change (increase/decrease) between two numbers

---

udfs/community/README.md
udfs/community/last_day.sql
udfs/community/month_ceil.sql
udfs/community/test_cases.yaml
udfs/migration/teradata/last_day.sql

Get the date representing the last day of the month.

Get last day of the month as date

---

tools/query_verification/src/main/java/com/google/bigquery/BigQuerySchemaJsonDeserializer.java
tools/query_verification/src/main/java/com/google/bigquery/QueryVerificationSchema.java
tools/query_verification/src/main/java/com/google/bigquery/QueryVerifier.java
tools/query_verification/src/test/java/com/google/bigquery/QueryVerifierTest.java
tools/query_verification/src/test/resources/schema1.json
tools/query_verification/src/test/resources/schema2.json

Implemented data free verification for schema provided as a JSON file.

Query Verification: Data free verification with json schema

---

tools/vscode_sql_extraction/.gitignore
tools/vscode_sql_extraction/.vscode/extensions.json
tools/vscode_sql_extraction/.vscode/launch.json
tools/vscode_sql_extraction/.vscode/settings.json
tools/vscode_sql_extraction/.vscode/tasks.json
tools/vscode_sql_extraction/package-lock.json
tools/vscode_sql_extraction/package.json
tools/vscode_sql_extraction/src/extension.ts
tools/vscode_sql_extraction/src/highlighter.ts
tools/vscode_sql_extraction/tsconfig.json

Highlights all query fragments and query usages. Different queries are highlighted in different colors.
Also un-gitignored the necessary .vscode folder that was autogenerated.

SQL Extraction: highlight queries in VS Code

---

.github/workflows/vscode-automatic-query-fixer.yml
tools/vscode_automatic_query_fixer/.eslintrc.json
tools/vscode_automatic_query_fixer/.gitignore
tools/vscode_automatic_query_fixer/.prettierrc.js
tools/vscode_automatic_query_fixer/.vscode/extensions.json
tools/vscode_automatic_query_fixer/.vscode/launch.json
tools/vscode_automatic_query_fixer/.vscode/settings.json
tools/vscode_automatic_query_fixer/.vscode/tasks.json
tools/vscode_automatic_query_fixer/.vscodeignore
tools/vscode_automatic_query_fixer/README.md
tools/vscode_automatic_query_fixer/package-lock.json
tools/vscode_automatic_query_fixer/package.json
tools/vscode_automatic_query_fixer/src/extension.ts
tools/vscode_automatic_query_fixer/src/test/runTest.ts
tools/vscode_automatic_query_fixer/src/test/suite/extension.test.ts
tools/vscode_automatic_query_fixer/src/test/suite/index.ts
tools/vscode_automatic_query_fixer/tsconfig.json
tools/vscode_automatic_query_fixer/vsc-extension-quickstart.md

These are just starter files, so there's no actual code to look at yet. These files were either created by the VS Code extension scaffold generator or copied from the VS Code SQL Extraction extension.
I guess important files include the GitHub actions workflow yaml, package.json, and the readme.

Auto Fixer: setup vscode project and CI

---

tools/query_verification/src/main/java/com/google/bigquery/BigQueryManager.java
tools/query_verification/src/main/java/com/google/bigquery/DataWarehouseManager.java
tools/query_verification/src/main/java/com/google/bigquery/QueryJobResults.java
tools/query_verification/src/main/java/com/google/bigquery/QueryVerifier.java
tools/query_verification/src/test/java/com/google/bigquery/BigQueryManagerTest.java
tools/query_verification/src/test/java/com/google/bigquery/MainTest.java
tools/query_verification/src/test/resources/query1.sql

Moved code communicating with BQ to its own class and updated the way query results are stored. Also updated output statistics.

Query Verification: Reorganized BQ verification code

---

tools/zetasql_helper/Dockerfile
tools/zetasql_helper/README.md
tools/zetasql_helper/zetasql_helper/fixer/BUILD
tools/zetasql_helper/zetasql_helper/fixer/fix_column_not_grouped.cc
tools/zetasql_helper/zetasql_helper/fixer/fix_column_not_grouped.h
tools/zetasql_helper/zetasql_helper/fixer/fix_duplicate_columns.cc
tools/zetasql_helper/zetasql_helper/fixer/fix_duplicate_columns.h
tools/zetasql_helper/zetasql_helper/fixer/fixer_test.cpp
tools/zetasql_helper/zetasql_helper/local_service/BUILD
tools/zetasql_helper/zetasql_helper/local_service/local_service.cc
tools/zetasql_helper/zetasql_helper/local_service/local_service.h
tools/zetasql_helper/zetasql_helper/local_service/local_service.proto
tools/zetasql_helper/zetasql_helper/local_service/local_service_grpc.cc
tools/zetasql_helper/zetasql_helper/local_service/local_service_grpc.h
tools/zetasql_helper/zetasql_helper/local_service/local_service_test.cc
tools/zetasql_helper/zetasql_helper/scanner/extract_function.cc
tools/zetasql_helper/zetasql_helper/scanner/locate_table.cc
tools/zetasql_helper/zetasql_helper/util/util.cc
tools/zetasql_helper/zetasql_helper/util/util.h

implement the FixDuplicateColumns and FixColumnNotGrouped methods in ZetaSQL Helper.
Test cases are included.
Readme and Dockerfile are added.

Auto Query Fixer: implement the FixDuplicateColumns and FixColumnNotGrouped methods

---

tools/automatic_query_fixer/README.md
tools/automatic_query_fixer/src/main/java/com/google/cloud/bigquery/utils/queryfixer/cmd/QueryFixerOptions.java

Auto Query Fixer: Update Readme

---

udfs/community/README.md
udfs/community/test_cases.yaml
udfs/community/ts_session_group.sql
udfs/community/ts_slide.sql

Adding time series functions introduced in this blog [post](https://patrickdunn-87582.medium.com/time-series-analytics-with-bigquery-part-2-b143a34102b5) on using time series sliding windows and session windows

time series slide and session funcs

---

udfs/community/README.md
udfs/community/pi.sql
udfs/community/test_cases.yaml

This PR does the following:
1. adds a new UDF which just creates the value of pi 
2. edits the radians UDF such that it leverages this Pi UDF
I find having a dedicated function for Pi helpful in my organization and thought it would be good as a community contribution. 
Please review and I would appreciate any feedback. Thanks!

Add Pi UDF 

---

dashboards/system_tables/sql/job_execution.sql

Added SAFE_DIVIDE in job_execution.sql #227

---

udfs/community/README.md
udfs/community/degrees.sql

degrees is defined as
```
CREATE OR REPLACE FUNCTION fn.degrees(x ANY TYPE) AS (
180 * x / ACOS(-1)
);
```
this matches existing radians() defined as
```
CREATE OR REPLACE FUNCTION fn.radians(x ANY TYPE) AS (
ACOS(-1) * x / 180
);
```

Add function degrees(), reverse of existing function radians()

---

udfs/community/README.md

SSIA.
I found a nunnecessary items list in README.md.

fix(docs) remove unnecessary list items

---

udfs/community/README.md
udfs/community/test_cases.js
udfs/community/url_decode.sqlx
udfs/community/url_encode.sqlx

I implement a BigQuery UDF to convert url encode and url decode.
Thanks

Add UDF for url_encode / url_decode

---

udfs/deploy.yaml
udfs/tests/dataform_testing_framework/deploy_and_run_tests.sh

Modify deploy_and_run_tests so that UDFs can optionally be deployed and unit tested in bigquery-public-data.persistent_udfs dataset

Bq public data

---

udfs/community/README.md
udfs/community/cw_period_intersection.sqlx
udfs/community/cw_period_ldiff.sqlx
udfs/community/cw_period_rdiff.sqlx
udfs/community/test_cases.js

This PR contributes emulations for following operators:
1. P_INTERSECT
2. LDIFF
3. RDIFF

Contribute Translation Engine UDF for emulating Teradata's period operators

---

udfs/community/README.md
udfs/community/cw_array_stable_distinct.sqlx
udfs/community/test_cases.js

It's very generic, but for new we're only going to need it for emulation of array aggregate functions on distinct values with ordering.

Translation Engine UDF for array stable distinct helper.

---

tools/protobuf_export/Main.java
tools/protobuf_export/main.py

After https://github.com/GoogleCloudPlatform/bigquery-utils/pull/362 that added a code example in Go, two more languages were requested. Added Python and Java code samples.

Additional languages for proto export

---

scripts/optimization/largest_freq_read_tables_without_partitioning_or_clustering.sql
scripts/optimization/largest_tables_without_partitioning_or_clustering.sql

+ expand full table id for greate flexibility when querying table
+ group by fixed for accurate table sizes (previously agg sum for entire project instead of per table)
+ improved readability for group by
+ formatting

update largest tables scripts

---

udfs/community/cw_convert_base.sqlx
udfs/community/test_cases.js

Update `cw_convert_base` to return NULL when any of the input values is NULL.

UDF `cw_convert_base` should return NULL on NULL inputs.

---

udfs/community/cw_td_strtok.sqlx
udfs/community/test_cases.js

[UDF] strtok null safety

---

README.md

Include optimization in the top-level README.md

Update README.md to include optimization directory

---

README.md
scripts/README.md
scripts/optimization/README.md
scripts/optimization/daily_reservation_analysis.sql
scripts/optimization/hourly_slot_consumption_by_labels.sql
scripts/optimization/queries_grouped_by_hash.sql
scripts/optimization/queries_grouped_by_labels.sql

The Reservation Analysis script is similar to the Project Analysis script. Let's add this to make sure all scripts are available here.

Add the Reservation Analysis script

---

dashboards/system_tables/README.md

remove / for broken links in system_tables

---

tools/custom_java_jdbc_client/README.md
tools/custom_java_jdbc_client/pom.xml
tools/custom_java_jdbc_client/src/main/java/com/example/BQSimbaExample.java
tools/custom_java_jdbc_client/src/main/java/com/example/OAuthUserConfig.java
tools/custom_java_jdbc_client/src/main/java/com/example/OAuthUserType.java

Adds a code sample for creating a custom Java application that uses the BQ JDBC driver to execute queries. This includes guidance on setting up dependencies, a builder class to help with configuring authentication, and the client code to set up and submit queries.

BQ Simba JDBC Driver Custom Java Client Sample

---

udfs/community/test_cases.js
udfs/community/xml_to_json.sqlx

This PR changes the txml function ( change from simplifyLostLess() to just simplify() ) used to simplify the XML structure.

Make xml_to_json UDF emit JSON that is closer to the XML structure

---

stored_procedures/README.md
stored_procedures/bqml_generate_embeddings.sql

This is intended to mirror the functionality of our public script -- https://github.com/GoogleCloudPlatform/bigquery-ml-utils/blob/master/sql_scripts/remote_inference/structured_table_inference_loop_generate_embedding_example.sql

Add stored procedure for BQML Generate Embedding

---

scripts/optimization/README.md
scripts/optimization/storage_billing_model_savings_ddl.sql

- The user will be responsible for adjusting the pricing according to their region, and whether or not they want to enforce a smaller time travel period (default is keeping time travel the same), as well as a few other optional parameters found within the script itself

storage billing model ddl optimization script

---

release/terraform/main.tf
udfs/migration/oracle/README.md
udfs/migration/oracle/round_datetime.sqlx
udfs/migration/oracle/test_cases.js

Emulate Oracle's ROUND() function for dates

---

udfs/community/azimuth_to_geog_point.sqlx
udfs/community/test_cases.js

Refactor azimuth_to_geog_point udf function to add description and simply calculation logic.

Refactor azimuth_to_geog_point

---

notebooks/bigquery_geospatial_visualization.ipynb

Update choropleth to normalized metric / bike station density by neighborhood.

Update choropleth in bigquery_geospatial_visualization
